- name: couser info
  hosts: local
  connection: local
  vars:
   course: "devops"
   duration_in_hrs: 150 
   is_live_session: true
   topics:
   - linux
   - terraform
   - docker
   more_details:
     months: "5"
     trainer: "siva"
  tasks:
  - name: print  course information 
    debug:
      msg: 
      - "name: {{course}}"
      - "type: {{ course | type_debug }}"
      - "name: {{duration_in_hrs}}"
      - "type:{{duration_in_hrs | type_debug}}"
      - "name: {{is_live_session}}"
      - "type:{{is_live_session | type_debug}}"
      - "name: {{topics}}"
      - "type:{{topics | type_debug}}"
 