- name: installing softwares
  hosts: local
  connection: local
  tasks:
  - name: installing softwares
    package:
      name: "{{item}}"
    loop:
        - nginx
        - mysql
        - git
        - maven
    register: packages
  # - name: printing installed softwares
  #   debug:
  #     msg: "insatlling {{item}}"
  #   loop:
  #     - nginx
  #     - mysql
  #     - git
  #     - maven
