- name: installing softwares
  hosts: local
  connection: local
  tasks:
  - name: installing softwares
    package:
      name: "{{item}}"
      loop:
        - nginx
        - mysql
        - git
        - maven
  - name:
    debug:
      msg: "insatlling {{item}}"
