- name: installing softwares
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing softwares
    package:
      name: "{{item}}"
    loop:
        - nginx
        - mysql
        - git
        - maven
    register: packages
  - name: printing installed softwares
    debug:
      msg: "Installed softwares:{{item.item}}"
    loop: "{{packages.results}}"
  #   loop:
  #     - nginx
  #     - mysql
  #     - git
  #     - maven
