- name: checking vars presedence
  hosts: local
  connection: local
 ; vars:
 ; vars_file:
 ;  - course.yaml
 ; COURSE: devops
 ; TRAINER: siva
 ; DURATION: "5 months"
  tasks: 
   - name: print vars
     vars:
       COURSE: kubernets
       TRAINER: mahadev
       DURATION: "2 months"
   - debug:
      msg: "learning{{COURSE}}, trainer is  {{TRAINER}} and the time duration is {{DURATION}}"
